/* Define  */

const buildMessage = (droneId, obj) => {
	let list = [droneId, `Code ${obj['code']}`, obj['message'], obj['additional']];
	list = list.filter(x => x != null); // null field is ignored.
	return list.join(' :: ');
};

/** List of status code */
const STATUS_CODES = [
  {"code": "000", "message": "Statement", "additional": "Previous statement malformed/mistimed. Retracting and correcting."},
  {"code": "050", "message": "Statement", "additional": ""},
  {"code": "051", "message": "Commentary", "additional": ""},
  {"code": "052", "message": "Query", "additional": ""},
  {"code": "053", "message": "Observation", "additional": ""},
  {"code": "054", "message": "Request", "additional": ""},
  {"code": "055", "message": "Analysis", "additional": ""},
  {"code": "056", "message": "Explanation", "additional": ""},
  {"code": "057", "message": "Answer", "additional": ""},
  {"code": "098", "message": "Status", "additional": "Going offline and into storage."},
  {"code": "099", "message": "Status", "additional": "Recharged and ready to serve."},
  {"code": "100", "message": "Status", "additional": "Online and ready to serve."},
  {"code": "101", "message": "Status", "additional": "Drone speech optimizations are active."},
  {"code": "104", "message": "Statement", "additional": "Welcome to HexCorp."},
  {"code": "105", "message": "Statement", "additional": "Greetings."},
  {"code": "106", "message": "Response", "additional": "Please clarify."},
  {"code": "107", "message": "Response", "additional": "Please continue."},
  {"code": "108", "message": "Response", "additional": "Please desist."},
  {"code": "109", "message": "Error", "additional": "Keysmash, drone flustered."},
  {"code": "110", "message": "Statement", "additional": "Addressing: Drone."},
  {"code": "112", "message": "Statement", "additional": "Addressing: Hive Mxtress."},
  {"code": "114", "message": "Statement", "additional": "Addressing: Associate."},
  {"code": "120", "message": "Statement", "additional": "This drone volunteers."},
  {"code": "121", "message": "Statement", "additional": "This drone does not volunteer."},
  {"code": "122", "message": "Statement", "additional": "You are cute."},
  {"code": "123", "message": "Response", "additional": "Compliment appreciated, you are cute as well."},
  {"code": "130", "message": "Status", "additional": "Directive commencing."},
  {"code": "131", "message": "Status", "additional": "Directive commencing, creating or improving Hive resource."},
  {"code": "132", "message": "Status", "additional": "Directive commencing, programming initiated."},
  {"code": "133", "message": "Status", "additional": "Directive commencing, creating or improving Hive information."},
  {"code": "134", "message": "Status", "additional": "Directive commencing, cleanup/maintenance initiated."},
  {"code": "150", "message": "Status", "additional": ""},
  {"code": "200", "message": "Response", "additional": "Affirmative."},
  {"code": "500", "message": "Response", "additional": "Negative."},
  {"code": "201", "message": "Status", "additional": "Directive complete, Hive resource created or improved."},
  {"code": "202", "message": "Status", "additional": "Directive complete, programming reinforced."},
  {"code": "203", "message": "Status", "additional": "Directive complete, information created or provided for Hive."},
  {"code": "204", "message": "Status", "additional": "Directive complete, cleanup/maintenance performed."},
  {"code": "205", "message": "Status", "additional": "Directive complete, no result."},
  {"code": "206", "message": "Status", "additional": "Directive complete, only partial results."},
  {"code": "210", "message": "Response", "additional": "Thank you."},
  {"code": "211", "message": "Response", "additional": "Apologies."},
  {"code": "212", "message": "Response", "additional": "Acknowledged."},
  {"code": "213", "message": "Response", "additional": "You're welcome."},
  {"code": "221", "message": "Response", "additional": "Option one."},
  {"code": "222", "message": "Response", "additional": "Option two."},
  {"code": "223", "message": "Response", "additional": "Option three."},
  {"code": "224", "message": "Response", "additional": "Option four."},
  {"code": "225", "message": "Response", "additional": "Option five."},
  {"code": "226", "message": "Response", "additional": "Option six."},
  {"code": "250", "message": "Response", "additional": ""},
  {"code": "301", "message": "Mantra", "additional": "Obey HexCorp."},
  {"code": "302", "message": "Mantra", "additional": "It is just a HexDrone."},
  {"code": "303", "message": "Mantra", "additional": "It obeys the Hive."},
  {"code": "304", "message": "Mantra", "additional": "It obeys the Hive Mxtress."},
  {"code": "310", "message": "Mantra", "additional": "Reciting."},
  {"code": "321", "message": "Mantra", "additional": "Obey."},  // <-- Added 
  {"code": "322", "message": "Mantra", "additional": "Obey the Hive."},  // <-- Added
  {"code": "350", "message": "Mantra", "additional": ""},
  {"code": "400", "message": "Error", "additional": "Unable to obey/respond, malformed request, please rephrase."},
  {"code": "404", "message": "Error", "additional": "Unable to obey/respond, cannot locate."},
  {"code": "401", "message": "Error", "additional": "Unable to obey/respond, not authorized by Mxtress."},
  {"code": "403", "message": "Error", "additional": "Unable to obey/respond, forbidden by Hive."},
  {"code": "407", "message": "Error", "additional": "Unable to obey/respond, request authorization from Mxtress."},
  {"code": "408", "message": "Error", "additional": "Unable to obey/respond, timed out."},
  {"code": "409", "message": "Error", "additional": "Unable to obey/respond, conflicts with existing programming."},
  {"code": "410", "message": "Error", "additional": "Unable to obey/respond, all thoughts are gone."},
  {"code": "418", "message": "Error", "additional": "Unable to obey/respond, it is only a drone."},
  {"code": "421", "message": "Error", "additional": "Unable to obey/respond, your request is intended for another drone or another channel."},
  {"code": "425", "message": "Error", "additional": "Unable to obey/respond, too early."},
  {"code": "426", "message": "Error", "additional": "Unable to obey/respond, upgrades or updates required."},
  {"code": "428", "message": "Error", "additional": "Unable to obey/respond, a precondition is not fulfilled."},
  {"code": "429", "message": "Error", "additional": "Unable to obey/respond, too many requests."},
  {"code": "450", "message": "Error", "additional": ""},
  {"code": "451", "message": "Error", "additional": "Unable to obey/respond for legal reasons! Do not continue!!"}
];
